development:
  adapter: postgresql
  database: first_app_development
  host: localhost
  encoding: UTF-8
  user: first_app
  password: first_app
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: first_app_development
  host: localhost
  encoding: UTF-8
  user: first_app
  password: first_app
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: first_app_development
  host: localhost
  encoding: UTF-8
  user: first_app
  password: first_app
  pool: 5
  timeout: 5000
